version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bot-ethority"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2ehqqh9o6nan"
s3_prefix = "bot-ethority"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
